---
version: 2
updates:
  # Enable GitHub Actions updates
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions

  # Enable npm updates
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      # UTC
      time: '08:00'
    labels:
      - dependencies
      - npm
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: io-ts
        versions: ['2.x']
      - dependency-name: typescript
        versions: ['^4.8']
      - dependency-name: ts-morph
        versions: ['>=16']
      # Ignore all @types/nodes patch updates, since
      # this package updates so frequently
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-patch']
