version: 2
updates:
  # Enable GitHub Actions updates
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - '@BitGo/internal-tools'
    labels:
      - dependencies
      - github-actions
    target-branch: beta

  # Enable npm updates
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      # UTC
      time: '08:00'
    reviewers:
      - '@BitGo/internal-tools'
    labels:
      - dependencies
      - npm
    target-branch: beta
